version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Copy Google-Services JSON into App folder
          command: |
            echo $GOOGLE_SERVICES_JSON > app/google-services.json
      - run:
          name: Run Detekt and check codebase
          command: |
            chmod +x ./gradlew
            ./gradlew detekt
      - run:
          name: Build debug APK and debug-test APK
          command: |
            ./gradlew :app:assembleDevDebug
            ./gradlew :app:assembleDevDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            gcloud firebase test android run \
              --type instrumentation \
              --use-orchestrator \
              --app app/build/outputs/apk/dev/debug/app-dev-debug.apk \
              --test app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk \
              --results-bucket circle-test-reports \
              --results-dir $CIRCLE_BUILD_NUM
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            pip install -U crcmod
            mkdir -p ~/gsutil/
            echo `gs://circle-test-reports/${CIRCLE_BUILD_NUM}`
            gsutil -m cp -r -U `gsutil ls gs://circle-test-reports/${CIRCLE_BUILD_NUM}/ 2> /dev/null || true` ~/gsutil/ | true
      - store_artifacts:
          path: ~/gsutil/
      - store_test_results:
          path: ~/gsutil/
